# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker login
        env : 
            dockerhub_username: ${{secrets.DOCKER_HUB_USERNAME}}
            dockerhub_password: ${{secrets.DOCKER_HUB_PASSWORD}}
            azure_registry_username: ${{secrets.AZURE_CONTAINER_REGISTRY_USERNAME}}
            azure_registry_password: ${{secrets.AZURE_CONTAINER_REGISTRY_PASSWORD}}
            azure_registry_login_server: ${{secrets.AZURE_COMTAINER_REGISTRY_LOGIN_SERVER}}
        run: |
            docker login -u $dockerhub_username -p $dockerhub_password
            
      - name: build docker image
        run: |
            docker build ./ -t computervisionsundi.azurecr.io/github_coco_yolov3:latest
            

      - uses: azure/docker-login@v1
        env : 
            dockerhub_username: ${{secrets.DOCKER_HUB_USERNAME}}
            dockerhub_password: ${{secrets.DOCKER_HUB_PASSWORD}}
            azure_registry_username: ${{secrets.AZURE_CONTAINER_REGISTRY_USERNAME}}
            azure_registry_password: ${{secrets.AZURE_CONTAINER_REGISTRY_PASSWORD}}
            azure_registry_login_server: ${{secrets.AZURE_COMTAINER_REGISTRY_LOGIN_SERVER}}
        with:
          login-server: '$azure_registry_login_server' 
          username: '$azure_registry_username'
          password: '$azure_registry_password'
          
      - name: push docker image
        run: |
            docker push computervisionsundi.azurecr.io/github_coco_yolov3:latest
          
          
          
      
          


          

        
